version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: notifyme_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: notifymedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notifyme_rabbitmq
    restart: always
    ports:
      - "5672:5672"     # RabbitMQ protocol
      - "15672:15672"   # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata:
